# Generated by Django 4.0.5 on 2022-06-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='角色', max_length=64)),
                ('desc', models.CharField(help_text='描述', max_length=256)),
            ],
            options={
                'db_table': 'tbl_role',
            },
        ),
    ]
