# Generated by Django 4.0.5 on 2022-06-11 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TblDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='需求内容')),
                ('delay', models.BooleanField(default=False, help_text='是否延期')),
                ('description', models.TextField(blank=True, help_text='项目描述', null=True)),
                ('status', models.CharField(default='plan', help_text='需求状态', max_length=32)),
                ('solvers', models.CharField(help_text='解决人', max_length=256)),
                ('start_date', models.DateField(help_text='开始日期')),
                ('end_date', models.DateField(help_text='结束日期')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('finish_time', models.DateTimeField(blank=True, help_text='完成时间', null=True)),
                ('creator', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, help_text='父级', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='demand.tbldemand')),
            ],
            options={
                'db_table': 'tbl_demand',
                'ordering': ('-create_time', '-finish_time'),
            },
        ),
        migrations.CreateModel(
            name='TblRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt_type', models.CharField(help_text='操作类型', max_length=16)),
                ('content', models.TextField(help_text='操作内容')),
                ('before_status', models.CharField(help_text='修改前需求状态', max_length=32)),
                ('after_status', models.CharField(help_text='修改前需求状态', max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('creator', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('demand', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='demand.tbldemand')),
            ],
            options={
                'db_table': 'tbl_record',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='TblProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='项目名称', max_length=64, unique=True)),
                ('version', models.CharField(help_text='项目版本', max_length=64)),
                ('delay', models.BooleanField(default=False, help_text='是否延期')),
                ('description', models.TextField(blank=True, help_text='项目描述', null=True)),
                ('status', models.CharField(default='plan', help_text='项目状态', max_length=32)),
                ('leader', models.CharField(default='', help_text='负责人', max_length=64)),
                ('start_date', models.DateField(help_text='开始日期')),
                ('end_date', models.DateField(help_text='结束日期')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('finish_time', models.DateTimeField(blank=True, help_text='完成时间', null=True)),
                ('creator', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, help_text='父级', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='demand.tblproject')),
            ],
            options={
                'db_table': 'tbl_project',
                'ordering': ('-create_time',),
            },
        ),
        migrations.AddField(
            model_name='tbldemand',
            name='project',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='demand.tblproject'),
        ),
    ]
